default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_tracker_development
  username: <%= ENV["BOOK_TRACKER_DATABASE_USERNAME"] %>
  password: <%= ENV["BOOK_TRACKER_DATABASE_PASSWORD"] %>


test:
  <<: *default
  database: book_tracker_test
  username: <%= ENV["BOOK_TRACKER_DATABASE_USERNAME"] %>
  password: <%= ENV["BOOK_TRACKER_DATABASE_PASSWORD"] %>


production:
  <<: *default
  database: book_tracker_production
  username: <%= ENV["BOOK_TRACKER_DATABASE_USERNAME"] %>
  password: <%= ENV["BOOK_TRACKER_DATABASE_PASSWORD"] %>
